dirs:
  - .
useGitIgnore: true
ignorePatterns:
  # Example addresses
  - pattern: "^http://localhost"
  - pattern: "^http://99.99.99.99"
  # Behind a login wall
  - pattern: "^https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/service-credentials/$"
  # https://git.zx2c4.com/wireguard-go gives status code 502 from time to time
  - pattern: "^https://git.zx2c4.com/wireguard-go$"
  # Reddit posts give status code 403 for Github Actions runners
  - pattern: "^https://www.reddit.com/r/.*$"
aliveStatusCodes:
  - 200
  - 206
  - 429
